name = "polishpal"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
NODE_ENV = "production"

# Environment variables - set these using: wrangler secret put OPENAI_API_KEY
# [env.production]
# vars = { NODE_ENV = "production" }
