name = "polishpal"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
cwd = "."

[build.environment]
NODE_VERSION = "18"

[[functions]]
directory = "functions"

[vars]
NODE_ENV = "production"
